#!/bin/bash

CONFIG="$HOME/.config/wofi/menu-launcher/config"
STYLE="$HOME/.config/wofi/menu-launcher/style.css"

if pgrep -x wofi >/dev/null; then
    pkill wofi
else
    wofi --show drun \
         --prompt "Search..." \
         --conf "$CONFIG" \
         --style "$STYLE"
fi
